// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: banc.proto

package ma.ahlam.stubs;

public final class Banc {
  private Banc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConvertcurrentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConvertcurrentRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    java.lang.String getCurrencyFrom();
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    com.google.protobuf.ByteString
        getCurrencyFromBytes();

    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    java.lang.String getCurrencyTo();
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    com.google.protobuf.ByteString
        getCurrencyToBytes();

    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code ConvertcurrentRequest}
   */
  public  static final class ConvertcurrentRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConvertcurrentRequest)
      ConvertcurrentRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertcurrentRequest.newBuilder() to construct.
    private ConvertcurrentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertcurrentRequest() {
      currencyFrom_ = "";
      currencyTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertcurrentRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConvertcurrentRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyTo_ = s;
              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.ahlam.stubs.Banc.ConvertcurrentRequest.class, ma.ahlam.stubs.Banc.ConvertcurrentRequest.Builder.class);
    }

    public static final int CURRENCYFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currencyFrom_;
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    public java.lang.String getCurrencyFrom() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    public com.google.protobuf.ByteString
        getCurrencyFromBytes() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCYTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currencyTo_;
    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    public java.lang.String getCurrencyTo() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    public com.google.protobuf.ByteString
        getCurrencyToBytes() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrencyFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currencyTo_);
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrencyFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currencyTo_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.ahlam.stubs.Banc.ConvertcurrentRequest)) {
        return super.equals(obj);
      }
      ma.ahlam.stubs.Banc.ConvertcurrentRequest other = (ma.ahlam.stubs.Banc.ConvertcurrentRequest) obj;

      if (!getCurrencyFrom()
          .equals(other.getCurrencyFrom())) return false;
      if (!getCurrencyTo()
          .equals(other.getCurrencyTo())) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCYFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyFrom().hashCode();
      hash = (37 * hash) + CURRENCYTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyTo().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.ahlam.stubs.Banc.ConvertcurrentRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConvertcurrentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConvertcurrentRequest)
        ma.ahlam.stubs.Banc.ConvertcurrentRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.ahlam.stubs.Banc.ConvertcurrentRequest.class, ma.ahlam.stubs.Banc.ConvertcurrentRequest.Builder.class);
      }

      // Construct using ma.ahlam.stubs.Banc.ConvertcurrentRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencyFrom_ = "";

        currencyTo_ = "";

        amount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentRequest_descriptor;
      }

      @java.lang.Override
      public ma.ahlam.stubs.Banc.ConvertcurrentRequest getDefaultInstanceForType() {
        return ma.ahlam.stubs.Banc.ConvertcurrentRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ma.ahlam.stubs.Banc.ConvertcurrentRequest build() {
        ma.ahlam.stubs.Banc.ConvertcurrentRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.ahlam.stubs.Banc.ConvertcurrentRequest buildPartial() {
        ma.ahlam.stubs.Banc.ConvertcurrentRequest result = new ma.ahlam.stubs.Banc.ConvertcurrentRequest(this);
        result.currencyFrom_ = currencyFrom_;
        result.currencyTo_ = currencyTo_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.ahlam.stubs.Banc.ConvertcurrentRequest) {
          return mergeFrom((ma.ahlam.stubs.Banc.ConvertcurrentRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.ahlam.stubs.Banc.ConvertcurrentRequest other) {
        if (other == ma.ahlam.stubs.Banc.ConvertcurrentRequest.getDefaultInstance()) return this;
        if (!other.getCurrencyFrom().isEmpty()) {
          currencyFrom_ = other.currencyFrom_;
          onChanged();
        }
        if (!other.getCurrencyTo().isEmpty()) {
          currencyTo_ = other.currencyTo_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.ahlam.stubs.Banc.ConvertcurrentRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.ahlam.stubs.Banc.ConvertcurrentRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currencyFrom_ = "";
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The currencyFrom.
       */
      public java.lang.String getCurrencyFrom() {
        java.lang.Object ref = currencyFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The bytes for currencyFrom.
       */
      public com.google.protobuf.ByteString
          getCurrencyFromBytes() {
        java.lang.Object ref = currencyFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyFrom() {
        
        currencyFrom_ = getDefaultInstance().getCurrencyFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The bytes for currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currencyTo_ = "";
      /**
       * <code>string currencyTo = 2;</code>
       * @return The currencyTo.
       */
      public java.lang.String getCurrencyTo() {
        java.lang.Object ref = currencyTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return The bytes for currencyTo.
       */
      public com.google.protobuf.ByteString
          getCurrencyToBytes() {
        java.lang.Object ref = currencyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyTo() {
        
        currencyTo_ = getDefaultInstance().getCurrencyTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The bytes for currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyTo_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConvertcurrentRequest)
    }

    // @@protoc_insertion_point(class_scope:ConvertcurrentRequest)
    private static final ma.ahlam.stubs.Banc.ConvertcurrentRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.ahlam.stubs.Banc.ConvertcurrentRequest();
    }

    public static ma.ahlam.stubs.Banc.ConvertcurrentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertcurrentRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConvertcurrentRequest>() {
      @java.lang.Override
      public ConvertcurrentRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConvertcurrentRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConvertcurrentRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConvertcurrentRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.ahlam.stubs.Banc.ConvertcurrentRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConvertcurrentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConvertcurrentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    java.lang.String getCurrencyFrom();
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    com.google.protobuf.ByteString
        getCurrencyFromBytes();

    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    java.lang.String getCurrencyTo();
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    com.google.protobuf.ByteString
        getCurrencyToBytes();

    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    double getResult();
  }
  /**
   * Protobuf type {@code ConvertcurrentResponse}
   */
  public  static final class ConvertcurrentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConvertcurrentResponse)
      ConvertcurrentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertcurrentResponse.newBuilder() to construct.
    private ConvertcurrentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertcurrentResponse() {
      currencyFrom_ = "";
      currencyTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertcurrentResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConvertcurrentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyTo_ = s;
              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            case 33: {

              result_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.ahlam.stubs.Banc.ConvertcurrentResponse.class, ma.ahlam.stubs.Banc.ConvertcurrentResponse.Builder.class);
    }

    public static final int CURRENCYFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currencyFrom_;
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    public java.lang.String getCurrencyFrom() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    public com.google.protobuf.ByteString
        getCurrencyFromBytes() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCYTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currencyTo_;
    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    public java.lang.String getCurrencyTo() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    public com.google.protobuf.ByteString
        getCurrencyToBytes() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private double result_;
    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    public double getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrencyFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currencyTo_);
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      if (result_ != 0D) {
        output.writeDouble(4, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrencyFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currencyTo_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (result_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.ahlam.stubs.Banc.ConvertcurrentResponse)) {
        return super.equals(obj);
      }
      ma.ahlam.stubs.Banc.ConvertcurrentResponse other = (ma.ahlam.stubs.Banc.ConvertcurrentResponse) obj;

      if (!getCurrencyFrom()
          .equals(other.getCurrencyFrom())) return false;
      if (!getCurrencyTo()
          .equals(other.getCurrencyTo())) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (java.lang.Double.doubleToLongBits(getResult())
          != java.lang.Double.doubleToLongBits(
              other.getResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCYFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyFrom().hashCode();
      hash = (37 * hash) + CURRENCYTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyTo().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getResult()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.ahlam.stubs.Banc.ConvertcurrentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConvertcurrentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConvertcurrentResponse)
        ma.ahlam.stubs.Banc.ConvertcurrentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.ahlam.stubs.Banc.ConvertcurrentResponse.class, ma.ahlam.stubs.Banc.ConvertcurrentResponse.Builder.class);
      }

      // Construct using ma.ahlam.stubs.Banc.ConvertcurrentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencyFrom_ = "";

        currencyTo_ = "";

        amount_ = 0D;

        result_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.ahlam.stubs.Banc.internal_static_ConvertcurrentResponse_descriptor;
      }

      @java.lang.Override
      public ma.ahlam.stubs.Banc.ConvertcurrentResponse getDefaultInstanceForType() {
        return ma.ahlam.stubs.Banc.ConvertcurrentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ma.ahlam.stubs.Banc.ConvertcurrentResponse build() {
        ma.ahlam.stubs.Banc.ConvertcurrentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.ahlam.stubs.Banc.ConvertcurrentResponse buildPartial() {
        ma.ahlam.stubs.Banc.ConvertcurrentResponse result = new ma.ahlam.stubs.Banc.ConvertcurrentResponse(this);
        result.currencyFrom_ = currencyFrom_;
        result.currencyTo_ = currencyTo_;
        result.amount_ = amount_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.ahlam.stubs.Banc.ConvertcurrentResponse) {
          return mergeFrom((ma.ahlam.stubs.Banc.ConvertcurrentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.ahlam.stubs.Banc.ConvertcurrentResponse other) {
        if (other == ma.ahlam.stubs.Banc.ConvertcurrentResponse.getDefaultInstance()) return this;
        if (!other.getCurrencyFrom().isEmpty()) {
          currencyFrom_ = other.currencyFrom_;
          onChanged();
        }
        if (!other.getCurrencyTo().isEmpty()) {
          currencyTo_ = other.currencyTo_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (other.getResult() != 0D) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.ahlam.stubs.Banc.ConvertcurrentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.ahlam.stubs.Banc.ConvertcurrentResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currencyFrom_ = "";
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The currencyFrom.
       */
      public java.lang.String getCurrencyFrom() {
        java.lang.Object ref = currencyFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The bytes for currencyFrom.
       */
      public com.google.protobuf.ByteString
          getCurrencyFromBytes() {
        java.lang.Object ref = currencyFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyFrom() {
        
        currencyFrom_ = getDefaultInstance().getCurrencyFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The bytes for currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currencyTo_ = "";
      /**
       * <code>string currencyTo = 2;</code>
       * @return The currencyTo.
       */
      public java.lang.String getCurrencyTo() {
        java.lang.Object ref = currencyTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return The bytes for currencyTo.
       */
      public com.google.protobuf.ByteString
          getCurrencyToBytes() {
        java.lang.Object ref = currencyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyTo() {
        
        currencyTo_ = getDefaultInstance().getCurrencyTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The bytes for currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyTo_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private double result_ ;
      /**
       * <code>double result = 4;</code>
       * @return The result.
       */
      public double getResult() {
        return result_;
      }
      /**
       * <code>double result = 4;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(double value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double result = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConvertcurrentResponse)
    }

    // @@protoc_insertion_point(class_scope:ConvertcurrentResponse)
    private static final ma.ahlam.stubs.Banc.ConvertcurrentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.ahlam.stubs.Banc.ConvertcurrentResponse();
    }

    public static ma.ahlam.stubs.Banc.ConvertcurrentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertcurrentResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConvertcurrentResponse>() {
      @java.lang.Override
      public ConvertcurrentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConvertcurrentResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConvertcurrentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConvertcurrentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.ahlam.stubs.Banc.ConvertcurrentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertcurrentRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertcurrentRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertcurrentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertcurrentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbanc.proto\"Q\n\025ConvertcurrentRequest\022\024\n" +
      "\014currencyFrom\030\001 \001(\t\022\022\n\ncurrencyTo\030\002 \001(\t\022" +
      "\016\n\006amount\030\003 \001(\001\"b\n\026ConvertcurrentRespons" +
      "e\022\024\n\014currencyFrom\030\001 \001(\t\022\022\n\ncurrencyTo\030\002 " +
      "\001(\t\022\016\n\006amount\030\003 \001(\001\022\016\n\006result\030\004 \001(\0012\236\002\n\013" +
      "Bankservice\022:\n\007convert\022\026.ConvertcurrentR" +
      "equest\032\027.ConvertcurrentResponse\022E\n\020getCu" +
      "rrentStream\022\026.ConvertcurrentRequest\032\027.Co" +
      "nvertcurrentResponse0\001\022B\n\rperformStream\022" +
      "\026.ConvertcurrentRequest\032\027.Convertcurrent" +
      "Response(\001\022H\n\021FullCurrentStream\022\026.Conver" +
      "tcurrentRequest\032\027.ConvertcurrentResponse" +
      "(\0010\001B\020\n\016ma.ahlam.stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConvertcurrentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConvertcurrentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertcurrentRequest_descriptor,
        new java.lang.String[] { "CurrencyFrom", "CurrencyTo", "Amount", });
    internal_static_ConvertcurrentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConvertcurrentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertcurrentResponse_descriptor,
        new java.lang.String[] { "CurrencyFrom", "CurrencyTo", "Amount", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
